### ISSUE TITLE
Can't execute any command in the Commands Folder

### ISSUE THREAD

**Issue by DImaste** [php-telegram-bot/core#1035]
Hi! I've set a webhook and always see the same error message:

`2019-12-28T02:06:26.457744+00:00 heroku[router]: at=info method=POST path="/hook.php" host=testing-php-bot.herokuapp.com request_id=e2fe5562-0aef-419c-afd9-6259d92f7efd fwd="91.108.6.61" dyno=web.1 connect=0ms service=2ms status=500 bytes=169 protocol=https
2019-12-28T02:06:26.461131+00:00 app[web.1]: [28-Dec-2019 02:06:26 UTC] PHP Fatal error:  Uncaught Error: Cannot call abstract method Longman\TelegramBot\Commands\Command::execute() in /app/vendor/longman/telegram-bot/src/Commands/UserCommands/StartCommand.php:55
2019-12-28T02:06:26.461181+00:00 app[web.1]: Stack trace:
2019-12-28T02:06:26.461395+00:00 app[web.1]: #0 /app/vendor/longman/telegram-bot/src/Commands/Command.php(182): Longman\TelegramBot\Commands\UserCommands\StartCommand->execute()
2019-12-28T02:06:26.461600+00:00 app[web.1]: #1 /app/vendor/longman/telegram-bot/src/Telegram.php(518): Longman\TelegramBot\Commands\Command->preExecute()
2019-12-28T02:06:26.461862+00:00 app[web.1]: #2 /app/vendor/longman/telegram-bot/src/Telegram.php(491): Longman\TelegramBot\Telegram->executeCommand('start')
2019-12-28T02:06:26.462104+00:00 app[web.1]: #3 /app/vendor/longman/telegram-bot/src/Telegram.php(416): Longman\TelegramBot\Telegram->processUpdate(Object(Longman\TelegramBot\Entities\Update))
2019-12-28T02:06:26.462207+00:00 app[web.1]: #4 /app/hook.php(23): Longman\TelegramBot\Telegram->handle()
2019-12-28T02:06:26.462234+00:00 app[web.1]: #5 {main}
2019-12-28T02:06:26.462424+00:00 app[web.1]:   thrown in /app/vendor/longman/telegram-bot/src/Commands/UserCommands/StartCommand.php on line 55
2019-12-28T02:06:26.462581+00:00 app[web.1]: 10.43.188.220 - - [28/Dec/2019:02:06:26 +0000] "POST /hook.php HTTP/1.1" 500 - "-" "-`

This is an unchanged command from the package. Composer info: 
"longman/telegram-bot": "^0.61.1"

**Comment by noplanman** [comment]
Nice catch, thanks. This is a bug and it happens when no custom `StartCommand` implementation has been done.

I've fixed this for the next release. In the meantime, you can create an own `StartCommand.php` and simply return an empty result.

You can basically copy this file here:
https://github.com/php-telegram-bot/core/blob/58c1c8b24dc8e0fe67151729f60b344b77dac872/src/Commands/UserCommands/StartCommand.php

**Comment by vladkireev** [comment]
Hi @noplanman, I'm added custom commands, call method addCommandsPaths with custom path and rewritten StartCommand, but StartCommand run from vendor Longman\TelegramBot\Commands\UserCommands\StartCommand, why?

**Comment by noplanman** [comment]
@vladkireev Did you copy the `StartCommand.php` from the vendor folder into your custom one?
As long as the filename, namespace and path to your custom commands folder are correct, it should work.

Maybe you could share your `hook.php` and custom `StartCommand.php` file to make it easier to help. (remember to remove any bot username and API key)

**Comment by bayanah** [comment]
please i have a probem ,my bot is not respond to any command..when i call in the url https://tath/to/set.php
its respond to wehook is set?but when i write any command it isnot respond

**Comment by adseipsum** [comment]
@noplanman Could you release it, please.

**Comment by noplanman** [comment]
@adseipsum Absolutely, in the coming days :+1:

**Comment by dzarezenko** [comment]
@noplanman What chance to receive an update on this week?

**Comment by noplanman** [comment]
@dzarezenko There are just a few pending PRs (#1066, #1067, #1068) that I'd like to get in.

I'd highly appreciate any reviewing or input on them.

My goal is to get the next release out this weekend!

**Comment by noplanman** [comment]
@dzarezenko A bit delayed, but version 0.62.0 has been released :tada: 

Thanks for your patience
