### ISSUE TITLE
SQL Import Structure Issue

### ISSUE THREAD

**Issue by FullDad** [php-telegram-bot/core#1363]
I can't figure this out.  I am a bit of a noob but i think this is the last piece to my puzzle.

I am importing per the instructions on the core documentation utf8mb4_unicode_520_ci and 17 tables import.

This is the query i am getting the error on.  I feel like if i fix this....i'll have my first telebot working!

any help would be apprciated.  I have tried to import this query with different tags and stuff but have had no luck.  Would love some help!

MySQL said: Documentation

#1267 - Illegal mix of collations (utf8mb4_general_ci,COERCIBLE) and (utf8mb4_unicode_520_ci,COERCIBLE) for operation '<>'

The Query:

( SELECT `User`, `Host`, `Select_priv`, `Insert_priv`, `Update_priv`, `Delete_priv`, `Create_priv`, `Drop_priv`, `Grant_priv`, `Index_priv`, `Alter_priv`, `References_priv`, `Create_tmp_table_priv`, `Lock_tables_priv`, `Create_view_priv`, `Show_view_priv`, `Create_routine_priv`, `Alter_routine_priv`, `Execute_priv`, `Event_priv`, `Trigger_priv`, '*' AS `Db`, 'g' AS `Type` FROM `mysql`.`user` WHERE NOT (`Select_priv` = 'N' AND `Insert_priv` = 'N' AND `Update_priv` = 'N' AND `Delete_priv` = 'N' AND `Create_priv` = 'N' AND `Drop_priv` = 'N' AND `Grant_priv` = 'N' AND `References_priv` = 'N' AND `Create_tmp_table_priv` = 'N' AND `Lock_tables_priv` = 'N' AND `Create_view_priv` = 'N' AND `Show_view_priv` = 'N' AND `Create_routine_priv` = 'N' AND `Alter_routine_priv` = 'N' AND `Execute_priv` = 'N' AND `Event_priv` = 'N' AND `Trigger_priv` = 'N')) UNION ( SELECT `User`, `Host`, `Select_priv`, `Insert_priv`, `Update_priv`, `Delete_priv`, `Create_priv`, `Drop_priv`, `Grant_priv`, `Index_priv`, `Alter_priv`, `References_priv`, `Create_tmp_table_priv`, `Lock_tables_priv`, `Create_view_priv`, `Show_view_priv`, `Create_routine_priv`, `Alter_routine_priv`, `Execute_priv`, `Event_priv`, `Trigger_priv`, `Db`, 'd' AS `Type` FROM `mysql`.`db` WHERE 'telebot4db' LIKE `Db`     AND NOT (`Select_priv` = 'N' AND `Insert_priv` = 'N' AND `Update_priv` = 'N' AND `Delete_priv` = 'N' AND `Create_priv` = 'N' AND `Drop_priv` = 'N' AND `Grant_priv` = 'N' AND `References_priv` = 'N' AND `Create_tmp_table_priv` = 'N' AND `Lock_tables_priv` = 'N' AND `Create_view_priv` = 'N' AND `Show_view_priv` = 'N' AND `Create_routine_priv` = 'N' AND `Alter_routine_priv` = 'N' AND `Execute_priv` = 'N' AND `Event_priv` = 'N' AND `Trigger_priv` = 'N')) ORDER BY `User` ASC, `Host` ASC, `Db` ASC;

**Comment by FullDad** [comment]
The error from trying to run getUpdatesCLI.php is below.

PHP Fatal error:  Uncaught TypeError: Argument 2 passed to Longman\TelegramBot\DB::insertTelegramUpdate() must be of the type int or null, float given, called in /var/www/html/vendor/longman/telegram-bot/src/DB.php on line 620 and defined in /var/www/html/vendor/longman/telegram-bot/src/DB.php:338
Stack trace:
#0 /var/www/html/vendor/longman/telegram-bot/src/DB.php(620): Longman\TelegramBot\DB::insertTelegramUpdate()
#1 /var/www/html/vendor/longman/telegram-bot/src/Telegram.php(644): Longman\TelegramBot\DB::insertRequest()
#2 /var/www/html/vendor/longman/telegram-bot/src/Telegram.php(516): Longman\TelegramBot\Telegram->processUpdate()
#3 /var/www/html/getUpdatesCLI.php(27): Longman\TelegramBot\Telegram->handleGetUpdates()
#4 {main}

**Comment by FullDad** [comment]
this is resolved.  can't be on 32 bit raspberry OS.

**Comment by FullDad** [comment]
i was on 32 bit os
