### ISSUE TITLE
execute a command on keyboard button press

### ISSUE THREAD

**Issue by rahimasgari** [php-telegram-bot/core#485]
### Required Information

- Operating system: centos 7
- PHP version: 7.1.4
- PHP Telegram Bot version: 0.44.1 
- Using MySQL database: no
- Update Method: Webhook
- Self-signed certificate: yes

Hi friends,
Thx for your great work.
I am new to telegram bot and have a problem.

I want to execute a command on keyboard button press (for example /test command) but i dont know how.

Here is my KeyboardCommand.php file:

```php
namespace Longman\TelegramBot\Commands\UserCommands;

use Longman\TelegramBot\Commands\UserCommand;
use Longman\TelegramBot\Entities\Keyboard;
use Longman\TelegramBot\Request;

/**
 * User "/keyboard" command
 */
class KeyboardCommand extends UserCommand
{
    /**
     * @var string
     */
    protected $name = 'keyboard';

    /**
     * @var string
     */
    protected $description = 'Show a custom keyboard with reply markup';

    /**
     * @var string
     */
    protected $usage = '/keyboard';

    /**
     * @var string
     */
    protected $version = '0.2.0';

    /**
     * Command execute method
     *
     * @return \Longman\TelegramBot\Entities\ServerResponse
     * @throws \Longman\TelegramBot\Exception\TelegramException
     */
    public function execute()
    {
        $keyboard = new Keyboard([
            ['text' => 'test', '' /* I DONT KNOW HOW TO TELL TO EXECUTE /test COMMAND HERE */]
        ]);

        //Return a random keyboard.
        $keyboard = $keyboard
            ->setResizeKeyboard(true)
            ->setOneTimeKeyboard(true)
            ->setSelective(false);

        $chat_id = $this->getMessage()->getChat()->getId();
        $data    = [
            'chat_id'      => $chat_id,
            'text'         => 'Press a Button:',
            'reply_markup' => $keyboard,
        ];

        return Request::sendMessage($data);
    }
}
```

Thx in advance :)

**Comment by ttvd94** [comment]
I don't think it can be possible, since telegram client app is listening to the keyboard events not your server.

**Comment by jacklul** [comment]
You have to read message output - use `GenericmessageCommand.php` for this.

Alternatively you can use `Conversation` feature to redirect all input to different command (in this case the command that will be handling comparing message content and assigning a command to execute).

**Comment by noplanman** [comment]
Using the `Conversation` method:

```php
<?php

namespace Longman\TelegramBot\Commands\UserCommands;

use Longman\TelegramBot\Commands\UserCommand;
use Longman\TelegramBot\Conversation;
use Longman\TelegramBot\Entities\Keyboard;
use Longman\TelegramBot\Entities\Update;
use Longman\TelegramBot\Request;

class ExecCommand extends UserCommand
{
    protected $name = 'exec';
    protected $description = 'Exec command';
    protected $usage = '/exec';
    protected $version = '1.0.0';

    public function execute()
    {
        $message = $this->getMessage();
        $chat    = $message->getChat();
        $chat_id = $chat->getId();
        $user_id = $message->getFrom()->getId();
        $text    = trim($message->getText(true));

        $data = [
            'chat_id' => $chat_id,
        ];
        if ($chat->isGroupChat() || $chat->isSuperGroup()) {
            $data['reply_markup'] = Keyboard::forceReply(['selective' => true]);
        }

        $conversation = new Conversation($user_id, $chat_id, $this->getName());

        if ($text === '') {
            $data['text']         = 'Choose something';
            $data['reply_markup'] = new Keyboard(['Need some help', 'Who am I?']);

            return Request::sendMessage($data);
        }

        $update = json_decode($this->update->toJson(), true);

        if ($text === 'Need some help') {
            $update['message']['text'] = '/help';
            $result = (new HelpCommand($this->telegram, new Update($update)))->preExecute();
        } elseif ($text === 'Who am I?') {
            $update['message']['text'] = '/whoami';
            $result = (new WhoamiCommand($this->telegram, new Update($update)))->preExecute();
        } else {
            $data['text'] = 'Invalid selection...';
            return Request::sendMessage($data);
        }

        $conversation->stop();
        return $result;
    }
}
```

@jacklul Is there any cleaner way to execute a command at the moment, that doesn't require the "changing the Update object" hack I always use?

**Comment by rahimasgari** [comment]
Thx for your reply.
I added the exec command. It displays the keyboard. But when i press Who am i or Need some help buttons it just displays related text but doesnt execute the command.

If i issue /whoami or /test commands they work.

**Comment by noplanman** [comment]
When you type something different instead of using the buttons, do you get `Invalid selection...`?

Do you have the error log enabled? Any error log entry?

**Comment by jacklul** [comment]
Why not just `$this->telegram->executeCommand("xxx")`?

**Comment by noplanman** [comment]
Hmm, was trying that but it kept on using the current Update object which has the wrong text in it, which is what gets used to execute.

Will need to try this again and dig deeper 👍

**Comment by rahimasgari** [comment]
@noplanman, no I dont get Invalid selection.
I have enabled log with this commands:
```
	Longman\TelegramBot\TelegramLog::initErrorLog(__DIR__ . '/' . $BOT_NAME . '_error.log');
	Longman\TelegramBot\TelegramLog::initDebugLog(__DIR__ . '/' . $BOT_NAME . '_debug.log');
	Longman\TelegramBot\TelegramLog::initUpdateLog(__DIR__ . '/' . $BOT_NAME . '_update.log');
```
But there is no error.

**Comment by noplanman** [comment]
Oh, just noticed that you don't use the database!

Try renaming the `execute()` method to `executeNoDb()`.

**Comment by rahimasgari** [comment]
@noplanman, the `execute()` method works and the keyboard appears, but the buttons doesnot work.
with `executeNoDb()` method the keyboard doesnot appear at all.

**Comment by noplanman** [comment]
@jacklul 
Try this, does it work for you? The help button doesn't execute `/help` properly for me.
(Using the main command from the top, replacing the `if` condition with this:
```php
$result = Request::emptyResponse();
if ($text === 'Need some help') {
    $this->getTelegram()->executeCommand('help');
} elseif ($text === 'Who am I?') {
    $this->getTelegram()->executeCommand('whoami');
} else {
...
}
```

Maybe it works for some commands, but it's not a clean solution for commands that depend on Update data.

@rahimasgari I just realised, you can only use conversations with a database.
So the only option you have, without a database, is to use `GenericmessageCommand.php` and put everything in there:

```php
protected $need_mysql = false;
public function execute()
{
    $message = $this->getMessage();
    $text    = trim($message->getText(true));

    $update = json_decode($this->update->toJson(), true);

    if ($text === 'Need some help') {
        $update['message']['text'] = '/help';
        return (new HelpCommand($this->telegram, new Update($update)))->preExecute();
    }
    if ($text === 'Who am I?') {
        $update['message']['text'] = '/whoami';
        return (new WhoamiCommand($this->telegram, new Update($update)))->preExecute();
    }

    return Request::emptyResponse();
}
```

**Comment by jacklul** [comment]
@noplanman It executes the command correctly in my case.

**Comment by noplanman** [comment]
> Didn't `executeCommand` previously accept Update object?

Not that I know of.

But, if you [look here](https://github.com/php-telegram-bot/core/blob/0.44.1/src/Telegram.php#L271), you'll see that the current Update object is used automatically, if none is provided by the method I used above.
And for this exact reason, just using `$telegram->executeCommand(...)` doesn't work, at least for me.

But why does it work for you? So strange 😕

**Comment by rahimasgari** [comment]
So this is my final code. but it doesnt work yet.

```
<?php

namespace Longman\TelegramBot\Commands\SystemCommands;

use Longman\TelegramBot\Commands\SystemCommand;
use Longman\TelegramBot\Entities\Keyboard;
use Longman\TelegramBot\Entities\Update;
use Longman\TelegramBot\Request;

class ExecCommand extends SystemCommand
{
    protected $name = 'exec';
    protected $description = 'Exec command';
    protected $usage = '/exec';
    protected $version = '1.0.0';
	protected $need_mysql = false;

    public function execute()
    {
        $message = $this->getMessage();
        $chat    = $message->getChat();
        $chat_id = $chat->getId();
        $user_id = $message->getFrom()->getId();
        $text    = trim($message->getText(true));

        $data = [
            'chat_id' => $chat_id,
        ];
        if ($chat->isGroupChat() || $chat->isSuperGroup()) {
            $data['reply_markup'] = Keyboard::forceReply(['selective' => true]);
        }

        if ($text === '') {
            $data['text']         = 'Choose something';
            $data['reply_markup'] = new Keyboard(['Need some help', 'Who am I?']);

            return Request::sendMessage($data);
        }


		$update = json_decode($this->update->toJson(), true);

		if ($text === 'Need some help') {
		    $update['message']['text'] = '/help';
		    return (new HelpCommand($this->telegram, new Update($update)))->preExecute();
		}
		if ($text === 'Who am I?') {
		    $update['message']['text'] = '/whoami';
		    return (new WhoamiCommand($this->telegram, new Update($update)))->preExecute();
		}

		return Request::emptyResponse();

    }
}
```

**Comment by noplanman** [comment]
Instead of `SystemCommand`, it must be `UserCommand`!

System commands are special commands that don't get called by users directly.

**Comment by rahimasgari** [comment]
At first I used `UserCommand` and then i changed it to `SystemCommand` (according to the `GenericmessageCommand.php`). 

At last i decided to enable mysql to make it work and it worked perfectly.
I think that it has a problem not using db.

Thx for your replies. :)

**Comment by noplanman** [comment]
I've tested it without a DB and it works.

I think there is a mixup of commands.

The following works for me:
*GenericmessageCommand.php*
```php
<?php

namespace Longman\TelegramBot\Commands\SystemCommands;

use Longman\TelegramBot\Commands\SystemCommand;
use Longman\TelegramBot\Commands\UserCommands\HelpCommand;
use Longman\TelegramBot\Commands\UserCommands\WhoamiCommand;
use Longman\TelegramBot\Entities\Update;
use Longman\TelegramBot\Request;

class GenericmessageCommand extends SystemCommand
{
    protected $name = 'Genericmessage';
    protected $description = 'Handle generic message';
    protected $version = '1.0.0';

    public function execute()
    {
        $text = trim($this->getMessage()->getText(true));

        $update = json_decode($this->update->toJson(), true);

        if ($text === 'Need some help') {
            $update['message']['text'] = '/help';
            return (new HelpCommand($this->telegram, new Update($update)))->preExecute();
        }
        if ($text === 'Who am I?') {
            $update['message']['text'] = '/whoami';
            return (new WhoamiCommand($this->telegram, new Update($update)))->preExecute();
        }

        return Request::emptyResponse();
    }
}
```

*ExecCommand.php*
```php
<?php

namespace Longman\TelegramBot\Commands\UserCommands;

use Longman\TelegramBot\Commands\UserCommand;
use Longman\TelegramBot\Entities\Keyboard;
use Longman\TelegramBot\Request;

class ExecCommand extends UserCommand
{
    protected $name = 'exec';
    protected $description = 'Exec command';
    protected $usage = '/exec';
    protected $version = '1.0.0';

    public function execute()
    {
        $data = [
            'chat_id'      => $this->getMessage()->getChat()->getId(),
            'text'         => 'Choose something',
            'reply_markup' => new Keyboard(['Need some help', 'Who am I?']),
        ];

        return Request::sendMessage($data);
    }
}
```

**Comment by noplanman** [comment]
@rahimasgari Did you get this to work, can I close here?

**Comment by Adizbek** [comment]
this works. I have tested with my bot.

**Comment by arkhub** [comment]
```
        if ($text === 'Need some help') {
            $update['message']['text'] = '/help';
            return (new HelpCommand($this->telegram, new Update($update)))->preExecute();
        }
        if ($text === 'Who am I?') {
            $update['message']['text'] = '/whoami';
            return (new WhoamiCommand($this->telegram, new Update($update)))->preExecute();
        }
```
is it better if the second "if" replaced by "elseif" ? so the checking will stop if condition is met.

**Comment by noplanman** [comment]
@arkhub That's not necessary, because of the `return` statement.
The second `if` never gets called if the first one is true.

**Comment by arkhub** [comment]
oh you're right, didn't see that one.

**Comment by sadeghesfahani** [comment]
$update = json_decode($this->update->toJson(), true);
$update['message']['text'] = '/signup';
return (new SignupCommand($this->telegram, new Update($update)))->preExecute();
it does not work for me! 
SignupCommand is an survey command.

**Comment by sharkydog** [comment]
You can also extend Telegram class and define a new function to ease executing commands
```php
public function executeCommandUpdate($command, \Longman\TelegramBot\Entities\Update $update) {
  $this->update = $update;
  return $this->executeCommand($command);
}
```

**Comment by MyZik** [comment]
@noplanman I'm so sorry for necroposting, but!
I tried to use that:

`GenericmessageCommand.php`
```php
public function execute()
    {
        $text = trim($this->getMessage()->getText(true));

        if ($text === '🔙 Balance') {
            $update['message']['text'] = '/balance';
            return (new BalanceCommand($this->telegram, new Update($update)))->preExecute();
        }

        if ($text === '🔙 To start') {
            $update['message']['text'] = '/start';
            return (new StartCommand($this->telegram, new Update($update)))->preExecute();
        }

        return Request::emptyResponse();
    }
```

And after I click at `🔙 Balance` button nothing happens and I've got an error:
```
PHP Fatal error:  Uncaught Error: Call to a member function getId() on null in /var/www/www-root/data/www/_/Commands/UserCommands/BalanceCommand.php:42\nStack trace:
#0 /var/www/www-root/data/www/_/vendor/longman/telegram-bot/src/Commands/Command.php(173): Longman\\TelegramBot\\Commands\\UserCommands\\BalanceCommand->execute()
#1 /var/www/www-root/data/www/s_/Commands/SystemCommands/GenericmessageCommand.php(48): Longman\\TelegramBot\\Commands\\Command->preExecute()
#2 /var/www/www-root/data/www/_/vendor/longman/telegram-bot/src/Commands/Command.php(173): Longman\\TelegramBot\\Commands\\SystemCommands\\GenericmessageCommand->execute()
#3 /var/www/www-root/data/www/_/vendor/longman/telegram-bot/src/Telegram.php(494): Longman\\TelegramBot\\Commands\\Command->preExecute()
#4 /var/www/www-root/data/www/_/vendor/longman/telegram-bot/src/Telegram.php(462): Longman\\TelegramBot\\Telegram->executeCommand('genericmessage')
#5 /var/www/www-root/dat in /var/www/www-root/data/www/_/Commands/UserCommands/BalanceCommand.php on line 42
```

And here is 42 line in BalanceCommand:
```php
$chat_id = $chat->getId();
```

For `🔙 To start` button I've got same problem.

Thanks in advance!

**Comment by noplanman** [comment]
You need to add this too, to get the correct Update object:
```php
$update = json_decode($this->update->toJson(), true);
```

**Comment by MyZik** [comment]
@noplanman oh, my bad :(
Thanks for your great work!

**Comment by rsukhar** [comment]
Here's my workaround - I'm just adding slashes to every non-slash commands so every input can be treated with a standard commands system.

1. Adding PSR7 Requests for Laravel:

```
composer require symfony/psr-http-message-bridge
composer require nyholm/psr7
```

2. Moving the Telegram Webhook to app/Http/Controllers/TelegramWebhookController.php:

```php
<?php

namespace App\Http\Controllers;

use Telegram\Bot\Laravel\Facades\Telegram;

class TelegramWebhookController extends Controller
{
    public function __invoke(\Psr\Http\Message\ServerRequestInterface $request)
    {
        $body = $request->getParsedBody();

        // Добавляем слеш перед сообщением, чтобы дальше Telegram SDK Kit все мог подцепить как команду
        // При этом не портим нормальные команды
        if (data_get($body, 'message.text') and ! str_starts_with($body['message']['text'], '/')) {
            $body['message']['text'] = '/' . data_get($body, 'message.text');
            $body['message']['entities'] = [
                [
                    'offset' => 0,
                    // Без mb_, потому что дальше в библиотеке команда на обрезание строки тоже без mb_
                    'length' => strlen($body['message']['text']),
                    'type' => 'bot_command',
                ],
            ];
            $request->getBody()->rewind();
            $request->getBody()->write(json_encode($body));
        }

        $update = Telegram::commandsHandler(true, $request);

        return 'ok';
    }
}
```

3. Adding the route:

```php
Route::post('/telegram_webhook/<token>/', \App\Http\Controllers\TelegramWebhookController::class)
    ->withoutMiddleware(['VerifyCsrfToken']);
```

4. Next I'm adding button texts as aliases to the Command classes:

```php
protected array $aliases = ['Main menu'];
```

And it just works, keeping the original clean Commands-classes system
