### ISSUE TITLE
List items from DB (InlineKeyboard)

### ISSUE THREAD

**Issue by MyZik** [php-telegram-bot/core#589]
Hi everyone!
In my db I have a table **_fruits_** with rows: _name_, _count_ and _price_. I need to list all items from that table with buttons "Next" and "Previous" in 1 message with InlineKeyboard.
How can I use that? It will be cool if you show an example...
Thanks in advance!

**Comment by MyZik** [comment]
Can anyone help me? :D

**Comment by noplanman** [comment]
Hi @MyZik!

Right, for a pagination with numbers, check out this new project:
https://github.com/php-telegram-bot/inline-keyboard-pagination

It doesn't support "Next" and "Previous" buttons just yet, but it's planned 👍

**Comment by MyZik** [comment]
@noplanman Thanks for your answer. Can this solution list items from table? To avoid having to assign the total number of pages manually... And how can I output any data on any page?
For example: page 10
Shows me data:
id: 10
name: Banana
message: yummm
and photo c:

How can I do that?

**Comment by noplanman** [comment]
Absolutely! It needs a fair bit of code though, here we go!

Here and example `/fruits` command (this can be further optimised, but it should illustrate how it works):
```php
<?php

namespace Longman\TelegramBot\Commands\AdminCommands;

use Longman\TelegramBot\Commands\UserCommand;
use Longman\TelegramBot\Entities\CallbackQuery;
use Longman\TelegramBot\Request;
use TelegramBot\InlineKeyboardPagination\Exceptions\InlineKeyboardPaginationException;
use TelegramBot\InlineKeyboardPagination\InlineKeyboardPagination;

class FruitsCommand extends UserCommand
{
    protected $name = 'fruits';
    protected $description = 'Display fruits, with inline pagination.';
    protected $usage = '/fruits';
    protected $version = '1.0.0';
    protected static $per_page = 3;

    /** @var array Fruits to display inline (can also be dynamically generated) */
    public static $fruits = [
        'apple'         => ['id' => 1, 'name' => 'Apple', 'message' => 'Mmhhh, delicious'],
        'orange'        => ['id' => 2, 'name' => 'Orange', 'message' => 'Mmhhh, delicious'],
        'cherry'        => ['id' => 3, 'name' => 'Cherry', 'message' => 'Mmhhh, delicious'],
        'banana'        => ['id' => 4, 'name' => 'Banana', 'message' => 'Mmhhh, delicious'],
        'mango'         => ['id' => 5, 'name' => 'Mango', 'message' => 'Mmhhh, delicious'],
        'passion_fruit' => ['id' => 6, 'name' => 'Passion fruit', 'message' => 'Mmhhh, delicious'],
    ];

    public static function callbackHandler(CallbackQuery $query)
    {
        $params = InlineKeyboardPagination::getParametersFromCallbackData($query->getData());
        if ($params['command'] !== 'fruits') {
            return null;
        }

        $data = [
            'chat_id'    => $query->getMessage()->getChat()->getId(),
            'message_id' => $query->getMessage()->getMessageId(),
            'text'       => 'Empty',
        ];

        // Using pagination
        if ($pagination = self::getInlineKeyboardPagination($params['newPage'])) {
            $data['text']         = self::getPaginationContent($pagination['items']);
            $data['reply_markup'] = [
                'inline_keyboard' => [$pagination['keyboard']],
            ];
        }

        return Request::editMessageText($data);
    }

    public static function getFruits()
    {
        return self::$fruits;
//        return DB::getPdo()->query('SELECT * FROM `fruits`')->fetchAll(PDO::FETCH_ASSOC);
    }

    public static function getPaginationContent(array $items)
    {
        $text = '';

        foreach ($items as $row) {
            $text .= "id: {$row['id']}\n";
            $text .= "name: {$row['name']}\n";
            $text .= "message: {$row['message']}\n";
        }

        return $text;
    }

    public static function getInlineKeyboardPagination($page = 1)
    {
        $fruits   = self::getFruits();

        if (empty($fruits)) {
            return null;
        }

        // Define inline keyboard pagination.
        $ikp = new InlineKeyboardPagination($fruits, 'fruits', $page, self::$per_page);

        // If item count changes, take wrong page clicks into account.
        try {
            $pagination = $ikp->getPagination();
        } catch (InlineKeyboardPaginationException $e) {
            $pagination = $ikp->getPagination(1);
        }

        return $pagination;
    }

    public function execute()
    {
        $data = [
            'chat_id' => $this->getMessage()->getChat()->getId(),
            'text'    => 'Empty',
        ];

        if ($pagination = self::getInlineKeyboardPagination(1)) {
            $data['text']         = self::getPaginationContent($pagination['items']);
            $data['reply_markup'] = [
                'inline_keyboard' => [$pagination['keyboard']],
            ];
        }

        return Request::sendMessage($data);
    }
}
```

Then, you need to register a callback in your `hook.php`:
```php
CallbackqueryCommand::addCallbackHandler([FruitsCommand::class, 'callbackHandler']);
```

That's it! Give this a try 😊 

To also add the picture, you'll need to use `Request::sendPhoto(...)` and also get the URL or Telegram ID of the photo to pass to it.

**Comment by MyZik** [comment]
@noplanman oh, https://github.com/php-telegram-bot/inline-keyboard-pagination is that required PHP 7? My server has 5.6 and I cann't install :(
Here is screenshot from console:  https://imgur.com/a/hogGE

**Comment by noplanman** [comment]
Yes, you'll need PHP7. Can you upgrade your server?

**Comment by MyZik** [comment]
@noplanman Standard version on the server - 5.6.30 and I installed version 7, but composer still doesn't see that :(
And I get an error from screenshot.
Debian 8, ISP Manager.

**Comment by MyZik** [comment]
@noplanman 
I get a very long error: 
```
[Sat Sep 23 14:31:57.469963 2017] [:error] [pid 26361] [client 149.154.167.226:41956] PHP Fatal error:  Uncaught Error: Class 'FruitsCommand' not found in /var/www/www-root/data/www/monero-qiwi.store/vendor/longman/telegram-bot/src/Commands/SystemCommands/CallbackqueryCommand.php:56\nStack trace:\n#0 /var/www/www-root/data/www/monero-qiwi.store/vendor/longman/telegram-bot/src/Commands/Command.php(173): Longman\\TelegramBot\\Commands\\SystemCommands\\CallbackqueryCommand->execute()\n#1 /var/www/www-root/data/www/monero-qiwi.store/vendor/longman/telegram-bot/src/Telegram.php(492): Longman\\TelegramBot\\Commands\\Command->preExecute()\n#2 /var/www/www-root/data/www/monero-qiwi.store/vendor/longman/telegram-bot/src/Telegram.php(460): Longman\\TelegramBot\\Telegram->executeCommand('callbackquery')\n#3 /var/www/www-root/data/www/monero-qiwi.store/vendor/longman/telegram-bot/src/Telegram.php(388): Longman\\TelegramBot\\Telegram->processUpdate(Object(Longman\\TelegramBot\\Entities\\Update))\n#4 /var/www/www-root/data/www/monero-qiwi.store/hook.php(37): Longman\\TelegramBot\\Telegram->handle()\n#5 {main}\n  thrown in /var/www/www-root/data/www/monero-qiwi.store/vendor/longman/telegram-bot/src/Commands/SystemCommands/CallbackqueryCommand.php on line 56
```
String 56: ```php
return DB::getPdo()->query('SELECT * FROM `fruits`')->fetchAll(PDO::FETCH_ASSOC);
```

**Comment by MyZik** [comment]
@noplanman a lot of thanks!!!

**Comment by MyZik** [comment]
Hi everyone again.
I have a field `photo` in my table `fruits`. It contains a file name in my /Uploads/Fruits/ folder. For example: `photo` = Banana.jpg (/Uploads/Fruits/Banana.jpg);
I want the photo to change, depending on the number of current page. (page 1 - banana photo, page 2 - strawberry photo etc.)
How can I get that field in InlineKeyboardPagination with sendPhoto? Here is my code now:
```php
<?php

namespace Longman\TelegramBot\Commands\AdminCommands;

use Longman\TelegramBot\Commands\UserCommand;
use Longman\TelegramBot\Entities\CallbackQuery;
use Longman\TelegramBot\Request;
use TelegramBot\InlineKeyboardPagination\Exceptions\InlineKeyboardPaginationException;
use TelegramBot\InlineKeyboardPagination\InlineKeyboardPagination;

class FruitsCommand extends UserCommand
{
    protected $name = 'fruits';
    protected $description = 'Display fruits, with inline pagination.';
    protected $usage = '/fruits';
    protected $version = '1.0.0';
    protected static $per_page = 1;

    public static function callbackHandler(CallbackQuery $query)
    {
        $params = InlineKeyboardPagination::getParametersFromCallbackData($query->getData());
        if ($params['command'] !== 'fruits') {
            return null;
        }

        $data = [
            'chat_id'    => $query->getMessage()->getChat()->getId(),
            'message_id' => $query->getMessage()->getMessageId(),
            'text'       => 'Empty',
        ];

       /**
         * TODO: Use sendPhoto (how to get a `photo` field in my table?)
         */
        // Using pagination
        if ($pagination = self::getInlineKeyboardPagination($params['newPage'])) {
            $data['text']         = self::getPaginationContent($pagination['items']);
            $data['reply_markup'] = [
                'inline_keyboard' => [$pagination['keyboard']],
            ];
        }

        return Request::editMessageText($data);
    }

    public static function getFruits()
    {
        return DB::getPdo()->query('SELECT * FROM `fruits`')->fetchAll(PDO::FETCH_ASSOC);
    }

    public static function getPaginationContent(array $items)
    {
        $text = '';

        foreach ($items as $row) {
            $text .= "id: {$row['id']}\n";
            $text .= "name: {$row['name']}\n";
            $text .= "message: {$row['message']}\n";
        }

        return $text;
    }

    public static function getInlineKeyboardPagination($page = 1)
    {
        $fruits   = self::getFruits();

        if (empty($fruits)) {
            return null;
        }

        // Define inline keyboard pagination.
        $ikp = new InlineKeyboardPagination($fruits, 'fruits', $page, self::$per_page);

        // If item count changes, take wrong page clicks into account.
        try {
            $pagination = $ikp->getPagination();
        } catch (InlineKeyboardPaginationException $e) {
            $pagination = $ikp->getPagination(1);
        }

        return $pagination;
    }

    public function execute()
    {
        $data = [
            'chat_id' => $this->getMessage()->getChat()->getId(),
            'text'    => 'Empty',
        ];

        /**
         * TODO: Use sendPhoto (how to get a `photo` field in my table?)
         */
        if ($pagination = self::getInlineKeyboardPagination(1)) {
            $data['text']         = self::getPaginationContent($pagination['items']);
            $data['reply_markup'] = [
                'inline_keyboard' => [$pagination['keyboard']],
            ];
        }

        return Request::sendMessage($data);
    }
}
```
@noplanman  @jacklul 
THANKS IN ADVANCE!

**Comment by Kurusa** [comment]
@noplanman, I tried your example and everything was going well, but here CallbackqueryCommand::addCallbackHandler([FruitsCommand::class, 'callbackHandler']); my script stoped. There is no "addCallbackHandler"

**Comment by noplanman** [comment]
What version of the bot do you have?
`addCallbackHandler(...)` was added in 0.46.0

**Comment by Kurusa** [comment]
I don`t know o.o where i can seethis version?

2018-05-22 0:36 GMT+03:00 Armando Lüscher <notifications@github.com>:

**Comment by noplanman** [comment]
In `vendor/longman/telegram-bot/Telegram.php` you can find the `$version` property.
If you've installed it via composer recently, you should have the latest 0.53.0
