### ISSUE TITLE
CallbackQuery fatal error on empty database

### ISSUE THREAD

**Issue by ginn13** [php-telegram-bot/core#808]
- Operating system: ubuntu 16.04
- PHP version: 7.0
- PHP Telegram Bot version: 0.52
- Using MySQL database: yes / no
- MySQL version: 5.5.52
- Update Method: Webhook
- Self-signed certificate: no
- RAW update (if available):

### Expected behaviour
I'm not sure about should bot ignore absent tables and continue to work without database or throw an exception (maybe warning).

### Actual behaviour
```
[23-Mar-2018 13:21:31 UTC] PHP Warning:  PDOStatement::execute(): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mydb.telegram_update' doesn't exist in /bot_folder/vendor/longman/telegram-bot/src/DB.php on line 207
[23-Mar-2018 13:21:31 UTC] PHP Warning:  PDOStatement::execute(): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mydb.chat' doesn't exist in /bot_folder/vendor/longman/telegram-bot/src/DB.php on line 472
[23-Mar-2018 13:21:31 UTC] PHP Warning:  PDOStatement::execute(): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mydb.user' doesn't exist in /bot_folder/vendor/longman/telegram-bot/src/DB.php on line 391
[23-Mar-2018 13:21:31 UTC] PHP Warning:  PDOStatement::execute(): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mydb.user_chat' doesn't exist in /bot_folder/vendor/longman/telegram-bot/src/DB.php on line 410
[23-Mar-2018 13:21:31 UTC] PHP Warning:  PDOStatement::execute(): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mydb.message' doesn't exist in /bot_folder/vendor/longman/telegram-bot/src/DB.php on line 925
[23-Mar-2018 13:21:31 UTC] PHP Warning:  PDOStatement::execute(): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mydb.conversation' doesn't exist in /bot_folder/vendor/longman/telegram-bot/src/ConversationDB.php on line 61
[23-Mar-2018 13:21:34 UTC] PHP Warning:  PDOStatement::execute(): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mydb.telegram_update' doesn't exist in /bot_folder/vendor/longman/telegram-bot/src/DB.php on line 207
[23-Mar-2018 13:21:34 UTC] PHP Warning:  PDOStatement::execute(): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mydb.chat' doesn't exist in /bot_folder/vendor/longman/telegram-bot/src/DB.php on line 472
[23-Mar-2018 13:21:34 UTC] PHP Warning:  PDOStatement::execute(): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mydb.user' doesn't exist in /bot_folder/vendor/longman/telegram-bot/src/DB.php on line 391
[23-Mar-2018 13:21:34 UTC] PHP Warning:  PDOStatement::execute(): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mydb.user_chat' doesn't exist in /bot_folder/vendor/longman/telegram-bot/src/DB.php on line 410
[23-Mar-2018 13:21:34 UTC] PHP Warning:  PDOStatement::execute(): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mydb.message' doesn't exist in /bot_folder/vendor/longman/telegram-bot/src/DB.php on line 925
[23-Mar-2018 13:21:34 UTC] PHP Warning:  PDOStatement::execute(): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mydb.request_limiter' doesn't exist in /bot_folder/vendor/longman/telegram-bot/src/DB.php on line 1135
[23-Mar-2018 13:21:34 UTC] PHP Warning:  PDOStatement::execute(): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mydb.request_limiter' doesn't exist in /bot_folder/vendor/longman/telegram-bot/src/DB.php on line 1178
[23-Mar-2018 13:21:37 UTC] PHP Warning:  PDOStatement::execute(): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mydb.telegram_update' doesn't exist in /bot_folder/vendor/longman/telegram-bot/src/DB.php on line 207
[23-Mar-2018 13:21:37 UTC] PHP Warning:  PDOStatement::execute(): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mydb.chat' doesn't exist in /bot_folder/vendor/longman/telegram-bot/src/DB.php on line 472
[23-Mar-2018 13:21:37 UTC] PHP Warning:  PDOStatement::execute(): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mydb.user' doesn't exist in /bot_folder/vendor/longman/telegram-bot/src/DB.php on line 391
[23-Mar-2018 13:21:37 UTC] PHP Warning:  PDOStatement::execute(): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mydb.user_chat' doesn't exist in /bot_folder/vendor/longman/telegram-bot/src/DB.php on line 410
[23-Mar-2018 13:21:37 UTC] PHP Warning:  PDOStatement::execute(): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mydb.message' doesn't exist in /bot_folder/vendor/longman/telegram-bot/src/DB.php on line 925
[23-Mar-2018 13:21:37 UTC] PHP Warning:  PDOStatement::execute(): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mydb.request_limiter' doesn't exist in /bot_folder/vendor/longman/telegram-bot/src/DB.php on line 1135
[23-Mar-2018 13:21:37 UTC] PHP Warning:  PDOStatement::execute(): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mydb.request_limiter' doesn't exist in /bot_folder/vendor/longman/telegram-bot/src/DB.php on line 1178
[23-Mar-2018 13:21:39 UTC] PHP Warning:  PDOStatement::execute(): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mydb.telegram_update' doesn't exist in /bot_folder/vendor/longman/telegram-bot/src/DB.php on line 207
[23-Mar-2018 13:21:39 UTC] PHP Warning:  PDOStatement::execute(): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mydb.user' doesn't exist in /bot_folder/vendor/longman/telegram-bot/src/DB.php on line 391
[23-Mar-2018 13:21:39 UTC] PHP Warning:  PDO::query(): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mydb.message' doesn't exist in /bot_folder/vendor/longman/telegram-bot/src/DB.php on line 728
[23-Mar-2018 13:21:39 UTC] PHP Fatal error:  Uncaught Error: Call to a member function rowCount() on boolean in /bot_folder/vendor/longman/telegram-bot/src/DB.php:730
Stack trace:
#0 /bot_folder/vendor/longman/telegram-bot/src/DB.php(580): Longman\TelegramBot\DB::insertCallbackQueryRequest(Object(Longman\TelegramBot\Entities\CallbackQuery))
#1 /bot_folder/vendor/longman/telegram-bot/src/Telegram.php(458): Longman\TelegramBot\DB::insertRequest(Object(Longman\TelegramBot\Entities\Update))
#2 /bot_folder/vendor/longman/telegram-bot/src/Telegram.php(388): Longman\TelegramBot\Telegram->processUpdate(Object(Longman\TelegramBot\Entities\Update))
#3 /bot_folder/class.napitki_bot.php(69): Longman\TelegramBot\Telegram->handle()
#4 /home/c/ce24895/wordpress_1/public_html/wp- in /bot_folder/vendor/longman/telegram-bot/src/DB.php on line 730
```

### Steps to reproduce
I used `$telegram->enableMySql()` with correct credentials to connect to database, but forgot to create tables. Most of command worked correctly until i tried to use `InlineKeyboard` from example-bot to run `Callbackquery`. Then I got an exception. If mysql not enabled then Callbackquery works. Therefore it doesn't need mysql to run. Considering other commands worked well such behaviour not so evident. Not sure it's a bug, just so you know.

**Comment by jacklul** [comment]
Not designed to work without created tables.

**Comment by noplanman** [comment]
If you want to use the database, you'll need to first import the database structure, which you can find in the `structure.sql` file in the root folder of the repository.

**Comment by ginn13** [comment]
of course, thanks. I meant that if db is empty or (faulty) wouldn't it be better to throw an exception or warning somewhere earlier? for example in `enableMySql()`.
